all:
	erlc -o ebin/ -I include/ src/webhttplisten.erl
	erlc -o ebin/ -I include/ src/httplib.erl
	erlc -o ebin/ -I include/ src/calendar_helper.erl
	erlc -o ebin/ -I include/ src/logger.erl
	erlc -o ebin/ -I include/ src/translate.erl
