    void            adaptiveThreshold ( const unsigned int width, const unsigned int height, const unsigned int offset = 0 );
    void            addNoise ( const NoiseType noiseType_ );
    void            affineTransform ( const DrawableAffine &affine );
    void            annotate ( const std::string &text_, const Geometry &location_ );
    void            annotate ( const std::string &text_, const Geometry &boundingArea_, const GravityType gravity_ );
    void            annotate ( const std::string &text_, const Geometry &boundingArea_, const GravityType gravity_, const double degrees_ );
//    void            annotate ( const std::string &text_, const GravityType gravity_ );
    void            blur ( const double radius_ = 0.0, const double sigma_ = 1.0  );
    void            border ( const Geometry &geometry_ = borderGeometryDefault );
    void            channel ( const ChannelType channel_ );
    void            channelDepth ( const ChannelType channel_, const unsigned int depth_ );
    unsigned int    channelDepth ( const ChannelType channel_ );
    void            charcoal ( const double radius_ = 0.0, const double sigma_ = 1.0 );
    void            chop ( const Geometry &geometry_ );
    void            colorize ( const unsigned int opacityRed_, const unsigned int opacityGreen_, const unsigned int opacityBlue_, const Color &penColor_ );
    void            colorize ( const unsigned int opacity_, const Color &penColor_ );
    void            comment ( const std::string &comment_ );
    void            compose (const CompositeOperator compose_);
    CompositeOperator compose ( void ) const;
    bool            compare ( const Image &reference_ );
//    void            composite ( const Image &compositeImage_, const int xOffset_, const int yOffset_, const CompositeOperator compose_ = InCompositeOp );
    void            composite ( const Image &compositeImage_, const Geometry &offset_, const CompositeOperator compose_ = InCompositeOp );
//    void            composite ( const Image &compositeImage_, const GravityType gravity_, const CompositeOperator compose_ = InCompositeOp );
    void            contrast ( const unsigned int sharpen_ );
    void            convolve ( const unsigned int order_, const double *kernel_ );
    void            crop ( const Geometry &geometry_ );
    void            cycleColormap ( const int amount_ );
    void            despeckle ( void );
    void            display ( void );
    void            draw ( const Drawable &drawable_ );
    void            draw ( const std::list<Magick::Drawable> &drawable_ );
    void            edge ( const double radius_ = 0.0 );
    void            emboss ( const double radius_ = 0.0, const double sigma_ = 1.0);
    void            enhance ( void );
    void            equalize ( void );
    void            erase ( void );
    void            flip ( void );
//    void            floodFillColor( const unsigned int x_, const unsigned int y_, const Color &fillColor_ );
    void            floodFillColor( const Geometry &point_, const Color &fillColor_ );
//    void            floodFillColor( const unsigned int x_, const unsigned int y_, const Color &fillColor_, const Color &borderColor_ );
    void            floodFillColor( const Geometry &point_, const Color &fillColor_, const Color &borderColor_ );
    void            floodFillOpacity ( const unsigned int x_, const unsigned int y_, const unsigned int opacity_, const PaintMethod method_ );
//    void            floodFillTexture( const unsigned int x_, const unsigned int y_, const Image &texture_ );
//    void            floodFillTexture( const Geometry &point_, const Image &texture_ );
//    void            floodFillTexture( const unsigned int x_, const unsigned int y_, const Image &texture_, const Color &borderColor_ );
    void            floodFillTexture( const Geometry &point_, const Image &texture_, const Color &borderColor_ );
    void            flop ( void );
    void            frame ( const Geometry &geometry_ = frameGeometryDefault );
    void            frame ( const unsigned int width_, const unsigned int height_, const int innerBevel_ = 6, const int outerBevel_ = 6 );
    void            gamma ( const double gamma_ );
    void            gamma ( const double gammaRed_, const double gammaGreen_, const double gammaBlue_ );
    void            gaussianBlur ( const double width_, const double sigma_ );
    void            implode ( const double factor_ );
    void            label ( const std::string &label_ );
    void            level ( const double black_point, const double white_point, const double mid_point=1.0 );
    void            levelChannel ( const ChannelType channel, const double black_point, const double white_point, const double mid_point=1.0 );
    void            magnify ( void );
    void            map ( const Image &mapImage_ , const bool dither_ = false );
//    void            matteFloodfill ( const Color &target_ , const unsigned int opacity_, const int x_, const PaintMethod method_ );
    void            medianFilter ( const double radius_ = 0.0 );
    void            minify ( void );
    void            modulate ( const double brightness_, const double saturation_, const double hue_ );
    void            negate ( const bool grayscale_ = false );
    void            normalize ( void );
    void            oilPaint ( const double radius_ = 3.0 );
    void            opacity ( const unsigned int opacity_ );
    void            opaque ( const Color &opaqueColor_, const Color &penColor_ );
    void            ping ( const std::string &imageSpec_ );
    void            ping ( const Blob &blob_ );
    void            quantize ( const bool measureError_ = false );
    void            quantumOperator ( const ChannelType channel_, const MagickEvaluateOperator operator_, Quantum rvalue_);
    void            quantumOperator ( const int x_, const unsigned int columns_, const unsigned int rows_, const ChannelType channel_, const MagickEvaluateOperator operator_, const Quantum rvalue_);
    void            process ( std::string name_, const int argc_, char **argv_ );
    void            raise ( const Geometry &geometry_ = raiseGeometryDefault, const bool raisedFlag_ = false );
    void            read ( const std::string &imageSpec_ );
    void            read ( const Geometry &size_, const std::string &imageSpec_ );
    void            read ( const Blob        &blob_ );
    void            read ( const Blob        &blob_, const Geometry    &size_ );
    void            read ( const Blob         &blob_, const Geometry     &size_, const unsigned int depth_ );
    void            read ( const Blob         &blob_, const Geometry     &size_, const unsigned int depth_, const std::string  &magick_ );
    void            read ( const Blob         &blob_, const Geometry     &size_, const std::string  &magick_ );
    void            read ( const unsigned int width_, const unsigned int height_, const std::string &map_, const StorageType  type_, const void        *pixels_ );
    void            reduceNoise ( void );
    void            reduceNoise ( const double order_ );
    void            roll ( const unsigned int columns_, const unsigned int rows_ );
    void            rotate ( const double degrees_ );
    void            sample ( const Geometry &geometry_ );
    void            scale ( const Geometry &geometry_ );
    void            segment ( const double clusterThreshold_ = 1.0, const double smoothingThreshold_ = 1.5 );
    void            shade ( const double azimuth_ = 30, const double elevation_ = 30, const bool   colorShading_ = false );
    void            sharpen ( const double radius_ = 0.0, const double sigma_ = 1.0 );
    void            shave ( const Geometry &geometry_ );
    void            shear ( const double xShearAngle_, const double yShearAngle_ );
    void            solarize ( const double factor_ = 50.0 );
    void            spread ( const unsigned int amount_ = 3 );
    void            stegano ( const Image &watermark_ );
    void            stereo ( const Image &rightImage_ );
    void            swirl ( const double degrees_ );
    void            texture ( const Image &texture_ );
    void            threshold ( const double threshold_ );
    void            transform ( const Geometry &imageGeometry_ );
    void            transform ( const Geometry &imageGeometry_, const Geometry &cropGeometry_  );
    void            transparent ( const Color &color_ );
    void            trim ( void );
    void            type ( const ImageType type_ );
    void            unsharpmask ( const double radius_, const double sigma_, const double amount_, const double threshold_ );
    void            wave ( const double amplitude_ = 25.0, const double wavelength_ = 150.0 );
    void            write ( const std::string &imageSpec_ );
    void            write ( Blob *blob_ );
    void            write ( Blob *blob_, const std::string &magick_ );
    void            write ( Blob *blob_, const std::string &magick_, const unsigned int depth_ );
    void            write ( const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const std::string& map_, const StorageType type_, void *pixels_ );
    void            zoom ( const Geometry &geometry_ );
